spring.application.name=inventory-api
spring.datasource.url=jdbc:postgresql://localhost:5432/pracdb
spring.datasource.username=postgres
spring.datasource.password=neemiah

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8080
